[mypy]
strict_optional = True
ignore_missing_imports = True
explicit_package_bases = True
mypy_path = .
exclude = (?x)(
    ^instance/
    | ^migrations/
    )

[mypy-application.models.*]
ignore_errors = True

[mypy-application.routes.*]
ignore_errors = True

[mypy-application.routes.achievement_routes]
ignore_errors = False
check_untyped_defs = True

[mypy-application.models.achievements]
ignore_errors = False
check_untyped_defs = True

[mypy-application.ai.*]
ignore_errors = True


