"""Add message_sending_enabled column

Revision ID: 28176d396310
Revises: 69050f7b3da8
Create Date: 2024-05-24 20:38:38.266716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28176d396310'
down_revision: Union[str, None] = '69050f7b3da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration', sa.Column('message_sending_enabled', sa.Boolean(), nullable=True, server_default='0'))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuration', 'message_sending_enabled')
    # ### end Alembic commands ###