"""Add banned words table

Revision ID: 30978dd57814
Revises: 28176d396310
Create Date: 2024-05-25 11:07:41.209927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30978dd57814'
down_revision: Union[str, None] = '28176d396310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned_words',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('word', sa.String(length=255), nullable=False),
                    sa.Column('added_on', sa.DateTime(), server_default=sa.func.current_timestamp(), nullable=False),
                    sa.Column('reason', sa.Text(), nullable=True),
                    sa.Column('active', sa.Boolean(), server_default=sa.true(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('word')
            ***REMOVED***
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banned_words')
    # ### end Alembic commands ###
