"""Add is_ai_teacher column to user table

Revision ID: 398487715c0e
Revises: 98b137519c44
Create Date: 2024-05-18 21:37:51.584476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398487715c0e'
down_revision: Union[str, None] = '98b137519c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_ai_teacher',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_ai_teacher',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
