/**
 * File: AdminPanel.jsx
 * Summary: Dynamic headless CRUD admin panel built with react-admin.
 *
 * Fields for every resource are auto-generated by fetching schema metadata from
 * the backend endpoint: GET /api/admin/crud/schema/<ResourceName>
 *
 * The backend returns the real SQLAlchemy column names, types, nullability, and
 * foreign key targets — so this panel stays in sync with the database automatically.
 *
 * Override configuration (FK references, hidden fields, read-only fields) lives in:
 *   ./adminSchema.js
 *
 * To add a new resource:
 *   1. Add the resource name to RESOURCES in adminSchema.js
 *   2. Add any FK_OVERRIDES for foreign key columns
 *   That's it — no JSX changes needed.
 */

import React, { useEffect, useState } from 'react';
import './AdminPanel.css';
import {
    Admin,
    AutocompleteInput,
    BooleanField,
    BooleanInput,
    Create,
    Datagrid,
    DateField,
    DateInput,
    DateTimeInput,
    Edit,
    FunctionField,
    Layout,
    List,
    Menu,
    NumberField,
    NumberInput,
    ReferenceField,
    ReferenceInput,
    Resource,
    SelectInput,
    SimpleForm,
    TextField,
    TextInput,
    Loading,
    defaultTheme,
} from 'react-admin';
import { Alert } from '@mui/material';
import dataProvider from './dataProvider';
import { FK_OVERRIDES, HIDDEN_FIELDS, READONLY_FIELDS, RESOURCES } from './adminSchema';
import client from '../api/client';

// ─── Schema Fetching ─────────────────────────────────────────────────────────

/** In-memory cache so each resource schema is only fetched once per page load. */
const _schemaCache = {};

async function fetchSchema(resourceName) {
    if (_schemaCache[resourceName]) return _schemaCache[resourceName];
    const res = await client.get(`/api/admin/crud/schema/${resourceName}`);
    _schemaCache[resourceName] = res.data.fields;
    return res.data.fields;
}

// ─── Field/Input Factories ────────────────────────────────────────────────────

/**
 * Given a column descriptor from the schema endpoint, return the correct
 * react-admin *display* component (used in List / Show views).
 */
function makeField(col, resourceName) {
    const key = `${resourceName}.${col.name}`;
    const fkOverride = FK_OVERRIDES[key];

    // Foreign key with a known reference override → ReferenceField
    if (fkOverride) {
        return (
            <ReferenceField key={col.name} source={col.name} reference={fkOverride.reference}>
                <TextField source={fkOverride.displayField} />
            </ReferenceField>
        );
    }

    const t = col.type; // e.g. "VARCHAR", "INTEGER", "BOOLEAN", "DATETIME", "TEXT"

    if (/^BOOL/i.test(t))                       return <BooleanField key={col.name} source={col.name} />;
    if (/^(INT|BIGINT|SMALLINT|FLOAT|NUMERIC)/i.test(t)) return <NumberField  key={col.name} source={col.name} />;
    if (/^(DATE|DATETIME|TIMESTAMP)/i.test(t))  return <DateField   key={col.name} source={col.name} showTime />;
    if (/^JSON/i.test(t)) {
        return (
            <FunctionField
                key={col.name}
                source={col.name}
                sortable={false}
                render={record => (record[col.name] == null ? '' : JSON.stringify(record[col.name]))}
            />
        );
    }

    // Fallback: text
    return <TextField key={col.name} source={col.name} />;
}

/** Maps the text typed in a ReferenceInput's autocomplete to the backend's `q` search. */
const searchToFilter = text => ({ q: text });

/**
 * JSON columns are edited as text. Text that does not parse yet is kept as a RawJsonText so
 * the input shows exactly what was typed and validateJson blocks saving it; a bare JSON
 * string value (which parses to a plain string) still round-trips.
 */
class RawJsonText {
    constructor(text) {
        this.text = text;
    }
}
const formatJson = value => {
    if (value == null) return '';
    return value instanceof RawJsonText ? value.text : JSON.stringify(value, null, 2);
};
const parseJson = text => {
    if (text == null || text === '') return null;
    try {
        return JSON.parse(text);
    } catch {
        return new RawJsonText(text);
    }
};
const validateJson = value => (value instanceof RawJsonText ? 'Invalid JSON' : undefined);

/**
 * Given a column descriptor, return the correct react-admin *input* component
 * (used in Create / Edit forms).
 */
function makeInput(col, resourceName, isCreate = false) {
    const key = `${resourceName}.${col.name}`;
    const fkOverride = FK_OVERRIDES[key];
    const isDisabled = col.primary_key || READONLY_FIELDS.has(col.name);

    // Primary key → disabled text unless creating Course or CourseInstance
    if (col.primary_key) {
        const canEditPK = isCreate && ["Course", "CourseInstance"].includes(resourceName);
        return <TextInput key={col.name} source={col.name} disabled={!canEditPK} />;
    }

    // Foreign key with a known reference override → searchable ReferenceInput showing displayField
    if (fkOverride) {
        return (
            <ReferenceInput key={col.name} source={col.name} reference={fkOverride.reference} perPage={25}>
                <AutocompleteInput
                    optionText={fkOverride.displayField}
                    filterToQuery={searchToFilter}
                    disabled={isDisabled}
                />
            </ReferenceInput>
        );
    }

    const t = col.type;

    // Enum columns only accept their declared values
    if (col.enums) {
        const choices = col.enums.map(value => ({ id: value, name: value }));
        return <SelectInput key={col.name} source={col.name} choices={choices} disabled={isDisabled} />;
    }

    if (/^BOOL/i.test(t))                        return <BooleanInput key={col.name} source={col.name} />;
    if (/^(INT|BIGINT|SMALLINT|FLOAT|NUMERIC)/i.test(t)) return <NumberInput  key={col.name} source={col.name} />;
    // DATETIME starts with DATE, so the time-carrying types must be tested first
    if (/^(DATETIME|TIMESTAMP)/i.test(t))        return <DateTimeInput key={col.name} source={col.name} disabled={isDisabled} />;
    if (/^DATE/i.test(t))                        return <DateInput   key={col.name} source={col.name} disabled={isDisabled} />;
    if (/^TEXT/i.test(t))                        return <TextInput   key={col.name} source={col.name} multiline disabled={isDisabled} />;
    if (/^JSON/i.test(t)) {
        return (
            <TextInput
                key={col.name}
                source={col.name}
                multiline
                format={formatJson}
                parse={parseJson}
                validate={validateJson}
                disabled={isDisabled}
            />
        );
    }

    return <TextInput key={col.name} source={col.name} disabled={isDisabled} />;
}

// ─── Dynamic Resource Components ─────────────────────────────────────────────

/**
 * A hook that fetches and returns the schema for a resource, filtering out
 * any hidden fields defined in adminSchema.js.
 */
function useSchema(resourceName) {
    // Tagged with the resource it belongs to, so a result for another resource is never shown
    const [result, setResult] = useState({ name: null, fields: null, error: null });

    useEffect(() => {
        let cancelled = false;
        const hidden = HIDDEN_FIELDS[resourceName] || new Set();
        fetchSchema(resourceName)
            .then(cols => {
                if (!cancelled) setResult({ name: resourceName, fields: cols.filter(c => !hidden.has(c.name)), error: null });
            })
            .catch(err => {
                if (!cancelled) setResult({ name: resourceName, fields: null, error: err.response?.data?.error || err.message });
            });
        return () => { cancelled = true; };
    }, [resourceName]);

    return result.name === resourceName ? result : { fields: null, error: null };
}

/** What a view shows until its schema has arrived: a spinner, or an alert if loading failed. */
function SchemaState({ error, resourceName }) {
    if (error) {
        return (
            <Alert severity="error" className="admin-schema-error">
                Could not load the {resourceName} schema: {error}
            </Alert>
        );
    }
    return <Loading />;
}

/** List view — shows all non-hidden columns as a datagrid. */
function DynamicList({ resourceName }) {
    const { fields, error } = useSchema(resourceName);
    if (error || !fields) return <SchemaState error={error} resourceName={resourceName} />;

    return (
        <List>
            <Datagrid rowClick="edit">
                {fields.map(col => makeField(col, resourceName))}
            </Datagrid>
        </List>
    );
}

/** Edit view — shows all editable columns as a form. */
function DynamicEdit({ resourceName }) {
    const { fields, error } = useSchema(resourceName);
    if (error || !fields) return <SchemaState error={error} resourceName={resourceName} />;

    return (
        <Edit>
            <SimpleForm>
                {fields.map(col => makeInput(col, resourceName))}
            </SimpleForm>
        </Edit>
    );
}

/** Create view — shows all writable columns as a form (PKs excluded). */
function DynamicCreate({ resourceName }) {
    const { fields, error } = useSchema(resourceName);
    if (error || !fields) return <SchemaState error={error} resourceName={resourceName} />;

    return (
        <Create>
            <SimpleForm>
                {fields
                    .filter(col => !col.primary_key || ["Course", "CourseInstance"].includes(resourceName))
                    .map(col => makeInput(col, resourceName, true))}
            </SimpleForm>
        </Create>
    );
}

/**
 * Builds the react-admin <Resource> for a given resource name, wiring up
 * the three dynamic views above.
 */
function buildResource(name) {
    return (
        <Resource
            key={name}
            name={name}
            list={<DynamicList   resourceName={name} />}
            edit={<DynamicEdit   resourceName={name} />}
            create={<DynamicCreate resourceName={name} />}
        />
    );
}

// Built once and passed as elements (not inline components): <Admin> keeps the same views
// across AdminPanel re-renders instead of remounting them and dropping unsaved form input.
const RESOURCE_ELEMENTS = RESOURCES.map(buildResource);

// ─── Layout ──────────────────────────────────────────────────────────────────

const CustomTopMenu = () => (
    <ul className="admin-top-menu">
        {RESOURCES.map(name => (
            <Menu.ResourceItem key={name} name={name} />
        ))}
    </ul>
);

const CustomLayout = (props) => (
    <Layout {...props} menu={() => null} sidebar={() => null}>
        <CustomTopMenu />
        {props.children}
    </Layout>
);

// ─── Root ─────────────────────────────────────────────────────────────────────

const darkTheme = {
    ...defaultTheme,
    palette: {
        mode: 'dark',
    },
};

const AdminPanel = () => (
    <Admin
        dataProvider={dataProvider}
        basename="/admin/advanced-crud"
        layout={CustomLayout}
        theme={darkTheme}
    >
        {RESOURCE_ELEMENTS}
    </Admin>
);

export default AdminPanel;
