/**
 * File: AdminPanel.jsx
 * Summary: Dynamic headless CRUD admin panel built with react-admin.
 *
 * Fields for every resource are auto-generated by fetching schema metadata from
 * the backend endpoint: GET /api/admin/crud/schema/<ResourceName>
 *
 * The backend returns the real SQLAlchemy column names, types, nullability, and
 * foreign key targets — so this panel stays in sync with the database automatically.
 *
 * Override configuration (FK references, hidden fields, read-only fields) lives in:
 *   ./adminSchema.js
 *
 * To add a new resource:
 *   1. Add the resource name to RESOURCES in adminSchema.js
 *   2. Add any FK_OVERRIDES for foreign key columns
 *   That's it — no JSX changes needed.
 */

import React, { useEffect, useState } from 'react';
import {
    Admin,
    BooleanField,
    BooleanInput,
    Create,
    Datagrid,
    DateField,
    DateInput,
    Edit,
    Layout,
    List,
    Menu,
    NumberField,
    NumberInput,
    ReferenceField,
    ReferenceInput,
    Resource,
    SimpleForm,
    TextField,
    TextInput,
    Loading,
} from 'react-admin';
import dataProvider from './dataProvider';
import { FK_OVERRIDES, HIDDEN_FIELDS, READONLY_FIELDS, RESOURCES } from './adminSchema';
import client from '../api/client';

// ─── Schema Fetching ─────────────────────────────────────────────────────────

/** In-memory cache so each resource schema is only fetched once per page load. */
const _schemaCache = {};

async function fetchSchema(resourceName) {
    if (_schemaCache[resourceName]) return _schemaCache[resourceName];
    const res = await client.get(`/api/admin/crud/schema/${resourceName}`);
    _schemaCache[resourceName] = res.data.fields;
    return res.data.fields;
}

// ─── Field/Input Factories ────────────────────────────────────────────────────

/**
 * Given a column descriptor from the schema endpoint, return the correct
 * react-admin *display* component (used in List / Show views).
 */
function makeField(col, resourceName) {
    const key = `${resourceName}.${col.name}`;
    const fkOverride = FK_OVERRIDES[key];

    // Foreign key with a known reference override → ReferenceField
    if (fkOverride) {
        return (
            <ReferenceField key={col.name} source={col.name} reference={fkOverride.reference}>
                <TextField source={fkOverride.displayField} />
            </ReferenceField>
        );
    }

    const t = col.type; // e.g. "VARCHAR", "INTEGER", "BOOLEAN", "DATETIME", "TEXT"

    if (/^BOOL/i.test(t))                       return <BooleanField key={col.name} source={col.name} />;
    if (/^(INT|BIGINT|SMALLINT|FLOAT|NUMERIC)/i.test(t)) return <NumberField  key={col.name} source={col.name} />;
    if (/^(DATE|DATETIME|TIMESTAMP)/i.test(t))  return <DateField   key={col.name} source={col.name} showTime />;

    // Fallback: text
    return <TextField key={col.name} source={col.name} />;
}

/**
 * Given a column descriptor, return the correct react-admin *input* component
 * (used in Create / Edit forms).
 */
function makeInput(col, resourceName, isCreate = false) {
    const key = `${resourceName}.${col.name}`;
    const fkOverride = FK_OVERRIDES[key];
    const isDisabled = col.primary_key || READONLY_FIELDS.has(col.name);

    // Primary key → disabled text unless creating Course or CourseInstance
    if (col.primary_key) {
        const canEditPK = isCreate && ["Course", "CourseInstance"].includes(resourceName);
        return <TextInput key={col.name} source={col.name} disabled={!canEditPK} />;
    }

    // Foreign key with a known reference override → ReferenceInput
    if (fkOverride) {
        return (
            <ReferenceInput key={col.name} source={col.name} reference={fkOverride.reference} />
        );
    }

    const t = col.type;

    if (/^BOOL/i.test(t))                        return <BooleanInput key={col.name} source={col.name} />;
    if (/^(INT|BIGINT|SMALLINT|FLOAT|NUMERIC)/i.test(t)) return <NumberInput  key={col.name} source={col.name} />;
    if (/^(DATE|DATETIME|TIMESTAMP)/i.test(t))   return <DateInput   key={col.name} source={col.name} disabled={isDisabled} />;

    return <TextInput key={col.name} source={col.name} disabled={isDisabled} />;
}

// ─── Dynamic Resource Components ─────────────────────────────────────────────

/**
 * A hook that fetches and returns the schema for a resource, filtering out
 * any hidden fields defined in adminSchema.js.
 */
function useSchema(resourceName) {
    const [fields, setFields] = useState(null);
    const [error, setError]   = useState(null);

    useEffect(() => {
        const hidden = HIDDEN_FIELDS[resourceName] || new Set();
        fetchSchema(resourceName)
            .then(cols => setFields(cols.filter(c => !hidden.has(c.name))))
            .catch(err  => setError(err.message));
    }, [resourceName]);

    return { fields, error };
}

/** List view — shows all non-hidden columns as a datagrid. */
function DynamicList({ resourceName }) {
    const { fields, error } = useSchema(resourceName);
    if (error)   return <p style={{ color: 'red' }}>Schema error: {error}</p>;
    if (!fields) return <Loading />;

    return (
        <List>
            <Datagrid rowClick="edit">
                {fields.map(col => makeField(col, resourceName))}
            </Datagrid>
        </List>
    );
}

/** Edit view — shows all editable columns as a form. */
function DynamicEdit({ resourceName }) {
    const { fields, error } = useSchema(resourceName);
    if (error)   return <p style={{ color: 'red' }}>Schema error: {error}</p>;
    if (!fields) return <Loading />;

    return (
        <Edit>
            <SimpleForm>
                {fields.map(col => makeInput(col, resourceName))}
            </SimpleForm>
        </Edit>
    );
}

/** Create view — shows all writable columns as a form (PKs excluded). */
function DynamicCreate({ resourceName }) {
    const { fields, error } = useSchema(resourceName);
    if (error)   return <p style={{ color: 'red' }}>Schema error: {error}</p>;
    if (!fields) return <Loading />;

    return (
        <Create>
            <SimpleForm>
                {fields
                    .filter(col => !col.primary_key || ["Course", "CourseInstance"].includes(resourceName))
                    .map(col => makeInput(col, resourceName, true))}
            </SimpleForm>
        </Create>
    );
}

/**
 * Builds the react-admin <Resource> for a given resource name, wiring up
 * the three dynamic views above.
 */
function buildResource(name) {
    return (
        <Resource
            key={name}
            name={name}
            list={()    => <DynamicList   resourceName={name} />}
            edit={()    => <DynamicEdit   resourceName={name} />}
            create={()  => <DynamicCreate resourceName={name} />}
        />
    );
}

// ─── Layout ──────────────────────────────────────────────────────────────────

const CustomTopMenu = () => (
    <ul style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))',
        gap: '10px',
        padding: '20px',
        backgroundColor: 'var(--bg-primary)',
        borderBottom: '1px solid var(--border-subtle)',
        maxHeight: '35vh',
        overflowY: 'auto',
        marginBottom: '20px',
        borderRadius: '0 0 var(--radius-lg) var(--radius-lg)',
        boxShadow: 'var(--shadow-soft)',
        listStyle: 'none',
        margin: '0',
    }}>
        {RESOURCES.map(name => (
            <Menu.ResourceItem key={name} name={name} />
        ))}
    </ul>
);

const CustomLayout = (props) => (
    <Layout {...props} menu={() => null} sidebar={() => null}>
        <CustomTopMenu />
        {props.children}
    </Layout>
);

// ─── Root ─────────────────────────────────────────────────────────────────────

const AdminPanel = () => (
    <Admin
        dataProvider={dataProvider}
        basename="/admin/advanced-crud"
        layout={CustomLayout}
    >
        {RESOURCES.map(buildResource)}
    </Admin>
);

export default AdminPanel;
