"""Add ParentConnectionRequest and connection_code

Revision ID: 0308e648db69
Revises: 1420d3de6924
Create Date: 2026-06-05 14:10:21.698236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0308e648db69'
down_revision = '1420d3de6924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_challenges')
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_challenges_classroom_id_classrooms'), 'classrooms', ['classroom_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('classroom_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_conversations_classroom_id_classrooms'), 'classrooms', ['classroom_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection_code', sa.String(length=10), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_connection_code'), ['connection_code'])
        batch_op.drop_column('has_seen_tutorial')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_seen_tutorial', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_users_connection_code'), type_='unique')
        batch_op.drop_column('connection_code')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_conversations_classroom_id_classrooms'), type_='foreignkey')
        batch_op.alter_column('classroom_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_challenges_classroom_id_classrooms'), type_='foreignkey')

    op.create_table('_alembic_tmp_challenges',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), nullable=False),
    sa.Column('domain', sa.VARCHAR(length=100), nullable=False),
    sa.Column('course_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=50), nullable=False),
    sa.Column('value', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('classroom_id', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_challenges_classroom_id_classrooms'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name=op.f('uq_challenges_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_challenges_slug'))
    )
    # ### end Alembic commands ###
