"""Sync prod schema

Revision ID: 0e51e941e868
Revises: a9f2e1d4b823
Create Date: 2026-07-02 10:06:52.774777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e51e941e868'
down_revision = 'a9f2e1d4b823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('animated_border_speed', sa.String(length=10), nullable=True))

    with op.batch_alter_table('store_items', schema=None) as batch_op:
        batch_op.drop_column('crowdfund_goal')
        batch_op.drop_column('is_crowdfunded')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('animated_border_speed', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('animated_border_speed')

    with op.batch_alter_table('store_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_crowdfunded', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('crowdfund_goal', sa.DOUBLE(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('animated_border_speed')

    # ### end Alembic commands ###
