"""add course instance request

Revision ID: 1217f40df1a9
Revises: 966744f7c74e
Create Date: 2026-07-19 14:18:06.180906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1217f40df1a9'
down_revision = '966744f7c74e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'course_instance_requests' not in inspector.get_table_names():
        op.create_table('course_instance_requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('student_id', sa.Integer(), nullable=False),
        sa.Column('course_instance_id', sa.String(length=64), nullable=False),
        sa.Column('requested_course_id', sa.String(length=64), nullable=True),
        sa.Column('url', sa.Text(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_course_instance_requests_student_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_course_instance_requests'))
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'course_instance_requests' in inspector.get_table_names():
        op.drop_table('course_instance_requests')
    # ### end Alembic commands ###
