"""Consolidate StandardProject

Revision ID: 15a65ee2d30b
Revises: a11cd4c0a073
Create Date: 2026-08-02 19:26:38.160688

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '15a65ee2d30b'
down_revision = 'a11cd4c0a073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standard_projects')
    with op.batch_alter_table('project_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('github_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('code_snippet', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_templates', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('code_snippet')
        batch_op.drop_column('video_url')
        batch_op.drop_column('github_link')
        batch_op.drop_column('link')

    op.create_table('standard_projects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('link', sa.VARCHAR(length=255), nullable=True),
    sa.Column('github_link', sa.VARCHAR(length=255), nullable=True),
    sa.Column('video_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('code_snippet', sa.TEXT(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standard_projects'))
    )
    # ### end Alembic commands ###
