"""enforce drawer unique constraint

Revision ID: 21c012e6da72
Revises: f907d00ca5ef
Create Date: 2026-06-17 10:43:55.351223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c012e6da72'
down_revision = 'f907d00ca5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_constraints = {c['name'] for c in inspector.get_unique_constraints('users')}

    if 'uq_users_drawer' not in existing_constraints:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.create_unique_constraint(batch_op.f('uq_users_drawer'), ['drawer'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_constraints = {c['name'] for c in inspector.get_unique_constraints('users')}

    if 'uq_users_drawer' in existing_constraints:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.drop_constraint(batch_op.f('uq_users_drawer'), type_='unique')

    # ### end Alembic commands ###
