"""enforce drawer unique constraint

Revision ID: 21c012e6da72
Revises: f907d00ca5ef
Create Date: 2026-06-17 10:43:55.351223

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '21c012e6da72'
down_revision = 'f907d00ca5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_drawer'), ['drawer'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_drawer'), type_='unique')

    # ### end Alembic commands ###
