"""Auto migration

Revision ID: 22210efa26d9
Revises: 1217f40df1a9
Create Date: 2026-07-25 09:34:34.717724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22210efa26d9'
down_revision = '1217f40df1a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    if 'classroom_join_attempts' in inspector.get_table_names():
        with op.batch_alter_table('classroom_join_attempts', schema=None) as batch_op:
            indexes = [idx['name'] for idx in inspector.get_indexes('classroom_join_attempts')]
            if 'ix_classroom_join_attempts_attempted_at' in indexes:
                batch_op.drop_index(batch_op.f('ix_classroom_join_attempts_attempted_at'))
            if 'ix_classroom_join_attempts_student_id' in indexes:
                batch_op.drop_index(batch_op.f('ix_classroom_join_attempts_student_id'))

        op.drop_table('classroom_join_attempts')

    if 'classrooms' in inspector.get_table_names():
        existing_cols = [c['name'] for c in inspector.get_columns('classrooms')]
        indexes = [idx['name'] for idx in inspector.get_indexes('classrooms')]
        with op.batch_alter_table('classrooms', schema=None) as batch_op:
            if 'url' not in existing_cols:
                batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=False, server_default=''))
            if 'course_id' not in existing_cols:
                batch_op.add_column(sa.Column('course_id', sa.String(length=64), nullable=True))
            if 'ix_classrooms_join_code' in indexes:
                batch_op.drop_index(batch_op.f('ix_classrooms_join_code'))
            if 'join_code' in existing_cols:
                batch_op.drop_column('join_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_code', sa.VARCHAR(length=5), nullable=True))
        batch_op.create_index(batch_op.f('ix_classrooms_join_code'), ['join_code'], unique=1)
        batch_op.drop_column('course_id')
        batch_op.drop_column('url')

    op.create_table('classroom_join_attempts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('attempted_at', sa.DATETIME(), nullable=False),
    sa.Column('code_attempted', sa.VARCHAR(length=10), nullable=False),
    sa.Column('success', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_classroom_join_attempts_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classroom_join_attempts'))
    )
    with op.batch_alter_table('classroom_join_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classroom_join_attempts_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_join_attempts_attempted_at'), ['attempted_at'], unique=False)

    # ### end Alembic commands ###
