"""add has_double_duck

Revision ID: 22b55c6153bd
Revises: 21c012e6da72
Create Date: 2026-06-19 10:01:44.630823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b55c6153bd'
down_revision = '21c012e6da72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing = {c['name'] for c in inspector.get_columns('users')}

    if 'has_double_duck' not in existing:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.add_column(sa.Column('has_double_duck', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing = {c['name'] for c in inspector.get_columns('users')}

    if 'has_double_duck' in existing:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.drop_column('has_double_duck')

    # ### end Alembic commands ###
