"""Remove ParentConnectionRequest

Revision ID: 39790c753ddf
Revises: 7326600b2699
Create Date: 2026-06-21 11:45:39.790799

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "39790c753ddf"
down_revision = "7326600b2699"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("parent_connection_requests")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parent_connection_requests",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("parent_id", sa.INTEGER(), nullable=False),
        sa.Column("student_id", sa.INTEGER(), nullable=False),
        sa.Column("relationship", sa.VARCHAR(length=50), nullable=False),
        sa.Column("message", sa.VARCHAR(length=500), nullable=True),
        sa.Column("status", sa.VARCHAR(length=20), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["users.id"],
            name=op.f("fk_parent_connection_requests_parent_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            name=op.f("fk_parent_connection_requests_student_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parent_connection_requests")),
    )
    # ### end Alembic commands ###
