"""add sequence to challenge

Revision ID: 39f391ff7765
Revises: fd82e37f7b2e
Create Date: 2026-08-01 13:31:23.894780

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = '39f391ff7765'
down_revision = 'fd82e37f7b2e'
branch_labels = None
depends_on = None


def _existing_columns(table_name):
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    return {c["name"] for c in inspector.get_columns(table_name)}


def _existing_indexes(table_name):
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    return {c["name"] for c in inspector.get_indexes(table_name)}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    existing_challenges = _existing_columns('challenges')
    if 'sequence' not in existing_challenges:
        with op.batch_alter_table('challenges', schema=None) as batch_op:
            batch_op.add_column(sa.Column('sequence', sa.Integer(), nullable=True))

    op.execute('UPDATE challenges SET sequence = id')

    existing_classrooms = _existing_columns('classrooms')
    existing_indexes = _existing_indexes('classrooms')
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        if 'join_code' not in existing_classrooms:
            batch_op.add_column(sa.Column('join_code', sa.String(5), nullable=True))
        if 'ix_classrooms_join_code' not in existing_indexes:
            batch_op.create_index(batch_op.f('ix_classrooms_join_code'), ['join_code'], unique=True)
        if 'course_id' in existing_classrooms:
            batch_op.drop_column('course_id')
        if 'url' in existing_classrooms:
            batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=255), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('course_id', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_classrooms_join_code'))

    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_column('sequence')

    # ### end Alembic commands ###
