"""Initial migration

Revision ID: 3a10e78a7fd0
Revises: 
Create Date: 2026-05-09 12:54:06.978506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a10e78a7fd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.alter_column('reward',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.create_unique_constraint(batch_op.f('uq_achievement_slug'), ['slug'])
        batch_op.drop_column('icon_class')

    with op.batch_alter_table('banned_words', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_banned_words_word'), ['word'])

    with op.batch_alter_table('challenge_logs', schema=None) as batch_op:
        batch_op.alter_column('helper',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.create_index(batch_op.f('ix_challenge_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_logs_username'), ['username'], unique=False)

    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_challenges_name'), ['name'])
        batch_op.create_unique_constraint(batch_op.f('uq_challenges_slug'), ['slug'])
        batch_op.create_foreign_key(batch_op.f('fk_challenges_classroom_id_classrooms'), 'classrooms', ['classroom_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.alter_column('duck_multiplier',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('classroom_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_conversations_creator_id_users'), 'users', ['creator_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_conversations_classroom_id_classrooms'), 'classrooms', ['classroom_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('course_instances', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
        batch_op.alter_column('classroom_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('course_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)

    with op.batch_alter_table('duck_trade_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duck_trade_log_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_duck_trade_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_duck_trade_log_username'), ['username'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('filename',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('session_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_skill_name_user', ['name', 'user_id'])

    with op.batch_alter_table('user_achievement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_achievement_achievement_id'), ['achievement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_achievement_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_user_achievement_user_id'), ['user_id', 'achievement_id'])

    with op.batch_alter_table('user_certificate', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('reviewed',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.create_unique_constraint(batch_op.f('uq_user_certificate_user_id'), ['user_id', 'achievement_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('nickname',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('earned_ducks',
               existing_type=sa.INTEGER(),
               type_=sa.Double(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('duck_balance',
               existing_type=sa.INTEGER(),
               type_=sa.Double(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('last_daily_duck',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.create_unique_constraint(batch_op.f('uq_users_slug'), ['slug'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])
        batch_op.drop_column('ducks')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ducks', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_slug'), type_='unique')
        batch_op.alter_column('last_daily_duck',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('duck_balance',
               existing_type=sa.Double(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('earned_ducks',
               existing_type=sa.Double(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('slug',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nickname',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('user_certificate', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_certificate_user_id'), type_='unique')
        batch_op.alter_column('reviewed',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))

    with op.batch_alter_table('user_achievement', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_achievement_user_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_achievement_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_achievement_achievement_id'))

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_constraint('uq_skill_name_user', type_='unique')

    with op.batch_alter_table('session_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_logs_user_id'))

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    with op.batch_alter_table('duck_trade_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duck_trade_log_username'))
        batch_op.drop_index(batch_op.f('ix_duck_trade_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_duck_trade_log_status'))

    with op.batch_alter_table('course_instances', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('classroom_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_conversations_classroom_id_classrooms'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_conversations_creator_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'classrooms', ['classroom_id'], ['id'])
        batch_op.alter_column('classroom_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.alter_column('duck_multiplier',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_challenges_classroom_id_classrooms'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'classrooms', ['classroom_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_challenges_slug'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_challenges_name'), type_='unique')

    with op.batch_alter_table('challenge_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_logs_username'))
        batch_op.drop_index(batch_op.f('ix_challenge_logs_timestamp'))
        batch_op.alter_column('helper',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))

    with op.batch_alter_table('banned_words', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_banned_words_word'), type_='unique')

    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_class', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_achievement_slug'), type_='unique')
        batch_op.alter_column('source',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('reward',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    op.create_table('_alembic_tmp_achievement',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.VARCHAR(length=256), nullable=True),
    sa.Column('type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('requirement_value', sa.VARCHAR(length=128), nullable=True),
    sa.Column('reward', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('source', sa.VARCHAR(length=255), server_default=sa.text('(NULL)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###
