"""Remove is_admin boolean

Revision ID: 4b8a6cfe12df
Revises: c1b4990c90c4
Create Date: 2026-08-03 13:33:34.662075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8a6cfe12df'
down_revision = 'c1b4990c90c4'
branch_labels = None
depends_on = None


def upgrade():
    # Data migration: Convert is_admin=True to role='admin'
    op.execute("UPDATE users SET role = 'admin' WHERE is_admin = 1")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###
