"""Remove is_admin boolean

Revision ID: 4b8a6cfe12df
Revises: c1b4990c90c4
Create Date: 2026-08-03 13:33:34.662075

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4b8a6cfe12df'
down_revision = 'c1b4990c90c4'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_cols = [col['name'] for col in inspector.get_columns('users')]

    if 'is_admin' in existing_cols:
        op.execute("UPDATE users SET role = 'admin' WHERE is_admin = 1")

    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'is_admin' in existing_cols:
            batch_op.drop_column('is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###
