"""packet_shop

Revision ID: 4f156a632ee3
Revises: 2d26b363a381
Create Date: 2026-06-07 23:18:06.115060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f156a632ee3'
down_revision = '2d26b363a381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_challenges')
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_challenges_classroom_id_classrooms'), 'classrooms', ['classroom_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('classroom_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_conversations_classroom_id_classrooms'), 'classrooms', ['classroom_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_chat_font', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_animated_border', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_golden_glow', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_custom_wallpaper', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_auto_claimer', sa.Boolean(), nullable=True))
        batch_op.drop_index(batch_op.f('uq_users_cognito_sub'))
        batch_op.create_unique_constraint(batch_op.f('uq_users_cognito_sub'), ['cognito_sub'])
        batch_op.drop_index(batch_op.f('uq_users_connection_code'))
        batch_op.create_unique_constraint(batch_op.f('uq_users_connection_code'), ['connection_code'])
        batch_op.drop_index(batch_op.f('uq_users_email'))
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.create_index(batch_op.f('uq_users_email'), ['email'], unique=1)
        batch_op.drop_constraint(batch_op.f('uq_users_connection_code'), type_='unique')
        batch_op.create_index(batch_op.f('uq_users_connection_code'), ['connection_code'], unique=1)
        batch_op.drop_constraint(batch_op.f('uq_users_cognito_sub'), type_='unique')
        batch_op.create_index(batch_op.f('uq_users_cognito_sub'), ['cognito_sub'], unique=1)
        batch_op.drop_column('has_auto_claimer')
        batch_op.drop_column('has_custom_wallpaper')
        batch_op.drop_column('has_golden_glow')
        batch_op.drop_column('has_animated_border')
        batch_op.drop_column('has_chat_font')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_conversations_classroom_id_classrooms'), type_='foreignkey')
        batch_op.alter_column('classroom_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_challenges_classroom_id_classrooms'), type_='foreignkey')

    op.create_table('_alembic_tmp_challenges',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), nullable=False),
    sa.Column('domain', sa.VARCHAR(length=100), nullable=False),
    sa.Column('course_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=50), nullable=False),
    sa.Column('value', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('classroom_id', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_challenges_classroom_id_classrooms'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name=op.f('uq_challenges_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_challenges_slug'))
    )
    # ### end Alembic commands ###
