"""Add can_chat to users

Revision ID: 561b9631c222
Revises: 9e1c493daf49
Create Date: 2026-07-03 09:51:19.110778

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = "561b9631c222"
down_revision = "9e1c493daf49"
branch_labels = None
depends_on = None


def _existing_columns(table_name):
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    return {c["name"] for c in inspector.get_columns(table_name)}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    existing_users = _existing_columns("users")
    if "can_chat" not in existing_users:
        with op.batch_alter_table("users", schema=None) as batch_op:
            batch_op.add_column(sa.Column("can_chat", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("can_chat")

    # ### end Alembic commands ###
