"""Add can_chat to users

Revision ID: 561b9631c222
Revises: 9e1c493daf49
Create Date: 2026-07-03 09:51:19.110778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561b9631c222'
down_revision = '9e1c493daf49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_chat', sa.Boolean(), nullable=True)) # noqa: lint-migrations

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('can_chat')

    # ### end Alembic commands ###
