"""add has_seen_tutorial

Revision ID: 58bd2b4d4732
Revises: 3a10e78a7fd0
Create Date: 2026-05-29 15:05:46.604569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '58bd2b4d4732'
down_revision = '3a10e78a7fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_seen_tutorial', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('has_seen_tutorial')
    # ### end Alembic commands ###
