"""add submissions table

Revision ID: 694b5ead6d52
Revises: 4b8a6cfe12df
Create Date: 2026-08-05 16:50:55.856129

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '694b5ead6d52'
down_revision = '4b8a6cfe12df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.String(length=64), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_submissions_classroom_id_classrooms')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_submissions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submissions'))
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_submissions_status'))
        batch_op.drop_index(batch_op.f('ix_submissions_classroom_id'))

    op.drop_table('submissions')
    # ### end Alembic commands ###
