"""add_student_active_track_and_track_requests_table

Revision ID: 6cafca745adc
Revises: d8c1054f03d2
Create Date: 2026-07-12 22:50:43.559987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cafca745adc'
down_revision = 'd8c1054f03d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    if inspector.has_table('_alembic_tmp_users'):
        op.drop_table('_alembic_tmp_users')

    if not inspector.has_table('track_change_requests'):
        op.create_table('track_change_requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('student_id', sa.Integer(), nullable=False),
        sa.Column('requester_type', sa.String(length=20), nullable=False),
        sa.Column('requested_track', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_track_change_requests_student_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_track_change_requests'))
        )
        
    users_columns = [c['name'] for c in inspector.get_columns('users')]

    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'active_track' not in users_columns:
            batch_op.add_column(sa.Column('active_track', sa.String(length=50), server_default='ozaria', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    users_columns = [c['name'] for c in inspector.get_columns('users')]
    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'active_track' in users_columns:
            batch_op.drop_column('active_track')

    if inspector.has_table('track_change_requests'):
        op.drop_table('track_change_requests')
    # ### end Alembic commands ###
