"""Auto migration

Revision ID: 707930904b7d
Revises: bb40896a0236
Create Date: 2026-08-18 18:35:52.963965

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '707930904b7d'
down_revision = 'bb40896a0236'
branch_labels = None
depends_on = None


def upgrade():
    # --- Ghost table cleanup (idempotency) ---
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if inspector.has_table('_alembic_tmp_users'):
        op.drop_table('_alembic_tmp_users')
    # -----------------------------------------

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('can_chat',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('can_chat',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###
