"""add standard project model

Revision ID: 7326600b2699
Revises: 940df4043dd3
Create Date: 2026-06-21 10:27:14.354073

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7326600b2699"
down_revision = "940df4043dd3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    if "standard_projects" not in existing_tables:
        op.create_table(
            "standard_projects",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(length=100), nullable=False),
            sa.Column("description", sa.Text(), nullable=True),
            sa.Column("link", sa.String(length=255), nullable=True),
            sa.Column("github_link", sa.String(length=255), nullable=True),
            sa.Column("video_url", sa.String(length=255), nullable=True),
            sa.Column("code_snippet", sa.Text(), nullable=True),
            sa.Column("image_url", sa.String(length=255), nullable=True),
            sa.PrimaryKeyConstraint("id", name=op.f("pk_standard_projects")),
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("standard_projects")
    # ### end Alembic commands ###
