"""Add chat perks to Message

Revision ID: 940df4043dd3
Revises: 22b55c6153bd
Create Date: 2026-06-19 10:45:22.596633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940df4043dd3'
down_revision = '22b55c6153bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_animated_border', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('chat_font_color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('chat_font_color')
        batch_op.drop_column('has_animated_border')

    # ### end Alembic commands ###
