"""Auto migration indexes
# lint: skip

Revision ID: 966744f7c74e
Revises: d1f659476137
Create Date: 2026-07-18 15:35:33.500949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966744f7c74e'
down_revision = 'd1f659476137'
branch_labels = None
depends_on = None

def has_index(inspector, table_name, index_name):
    try:
        indexes = inspector.get_indexes(table_name)
        return any(idx['name'] == index_name for idx in indexes)
    except Exception:
        return False

def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # ### commands auto generated by Alembic - please adjust! ###
    if not has_index(inspector, 'challenge_logs', 'ix_challenge_log_user_slug_instance'):
        with op.batch_alter_table('challenge_logs', schema=None) as batch_op:
            batch_op.create_index('ix_challenge_log_user_slug_instance', ['user_id', 'challenge_slug', 'course_instance'], unique=False)

    if not has_index(inspector, 'connection_attempts', 'ix_connection_attempts_attempted_at'):
        with op.batch_alter_table('connection_attempts', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_connection_attempts_attempted_at'), ['attempted_at'], unique=False)
            
    if not has_index(inspector, 'connection_attempts', 'ix_connection_attempts_parent_id'):
        with op.batch_alter_table('connection_attempts', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_connection_attempts_parent_id'), ['parent_id'], unique=False)

    if not has_index(inspector, 'duck_transactions', 'ix_duck_transactions_timestamp'):
        with op.batch_alter_table('duck_transactions', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_duck_transactions_timestamp'), ['timestamp'], unique=False)
            
    if not has_index(inspector, 'duck_transactions', 'ix_duck_transactions_user_id'):
        with op.batch_alter_table('duck_transactions', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_duck_transactions_user_id'), ['user_id'], unique=False)

    if not has_index(inspector, 'track_change_requests', 'ix_track_change_requests_student_id_status'):
        with op.batch_alter_table('track_change_requests', schema=None) as batch_op:
            batch_op.create_index('ix_track_change_requests_student_id_status', ['student_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # ### commands auto generated by Alembic - please adjust! ###
    if has_index(inspector, 'track_change_requests', 'ix_track_change_requests_student_id_status'):
        with op.batch_alter_table('track_change_requests', schema=None) as batch_op:
            batch_op.drop_index('ix_track_change_requests_student_id_status')

    if has_index(inspector, 'duck_transactions', 'ix_duck_transactions_user_id'):
        with op.batch_alter_table('duck_transactions', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_duck_transactions_user_id'))
            
    if has_index(inspector, 'duck_transactions', 'ix_duck_transactions_timestamp'):
        with op.batch_alter_table('duck_transactions', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_duck_transactions_timestamp'))

    if has_index(inspector, 'connection_attempts', 'ix_connection_attempts_parent_id'):
        with op.batch_alter_table('connection_attempts', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_connection_attempts_parent_id'))
            
    if has_index(inspector, 'connection_attempts', 'ix_connection_attempts_attempted_at'):
        with op.batch_alter_table('connection_attempts', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_connection_attempts_attempted_at'))

    if has_index(inspector, 'challenge_logs', 'ix_challenge_log_user_slug_instance'):
        with op.batch_alter_table('challenge_logs', schema=None) as batch_op:
            batch_op.drop_index('ix_challenge_log_user_slug_instance')
    # ### end Alembic commands ###
