"""add_is_auto_recommended_to_user_certificate

Revision ID: a11cd4c0a073
Revises: 39f391ff7765
Create Date: 2026-08-02 11:09:52.751931

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a11cd4c0a073'
down_revision = '39f391ff7765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if "classroom_join_attempts" not in existing_tables:
        op.create_table(
            "classroom_join_attempts",
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("student_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
            sa.Column("attempted_at", sa.DateTime(), nullable=False),
            sa.Column("code_attempted", sa.String(length=10), nullable=False),
            sa.Column("success", sa.Boolean(), default=False),
        )
        op.create_index("ix_classroom_join_attempts_student_id", "classroom_join_attempts", ["student_id"])
        op.create_index("ix_classroom_join_attempts_attempted_at", "classroom_join_attempts", ["attempted_at"])

    existing_cols = {c["name"] for c in inspector.get_columns("user_certificate")}

    with op.batch_alter_table("user_certificate", schema=None) as batch_op:
        if "is_auto_recommended" not in existing_cols:
            batch_op.add_column(
                sa.Column("is_auto_recommended", sa.Boolean(), nullable=True, server_default=sa.text("0"))
            )
        if "recommendation_reason" not in existing_cols:
            batch_op.add_column(
                sa.Column("recommendation_reason", sa.String(length=256), nullable=True)
            )

    op.execute(
        "UPDATE users SET last_daily_duck = NULL WHERE last_daily_duck IS NULL OR last_daily_duck = '(NULL)' OR typeof(last_daily_duck) != 'text'"
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if "classroom_join_attempts" in existing_tables:
        op.drop_table("classroom_join_attempts")

    existing_cols = {c["name"] for c in inspector.get_columns("user_certificate")}

    with op.batch_alter_table("user_certificate", schema=None) as batch_op:
        if "recommendation_reason" in existing_cols:
            batch_op.drop_column("recommendation_reason")
        if "is_auto_recommended" in existing_cols:
            batch_op.drop_column("is_auto_recommended")

    # ### end Alembic commands ###
