"""Remove course_id and url from Classroom

Revision ID: b2fd06ed54ab
Revises: c1d2e3f4a5b6
Create Date: 2026-07-24 21:13:03.876004

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = "b2fd06ed54ab"
down_revision = "c1d2e3f4a5b6"
branch_labels = None
depends_on = None


def _existing_columns(table_name):
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    return {c["name"] for c in inspector.get_columns(table_name)}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    existing_classrooms = _existing_columns("classrooms")
    with op.batch_alter_table("classrooms", schema=None) as batch_op:
        if "url" in existing_classrooms:
            batch_op.drop_column("url")
        if "course_id" in existing_classrooms:
            batch_op.drop_column("course_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("classrooms", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("course_id", sa.VARCHAR(length=64), nullable=True)
        )
        batch_op.add_column(sa.Column("url", sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
