"""add animated_border_color

Revision ID: c1b4990c90c4
Revises: 15a65ee2d30b
Create Date: 2026-08-02 23:50:09.814128

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c1b4990c90c4'
down_revision = '15a65ee2d30b'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    msg_cols = [col['name'] for col in inspector.get_columns('messages')]
    with op.batch_alter_table('messages', schema=None) as batch_op:
        if 'animated_border_color' not in msg_cols:
            batch_op.add_column(sa.Column('animated_border_color', sa.String(length=7), nullable=True))

    user_cols = [col['name'] for col in inspector.get_columns('users')]
    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'animated_border_color' not in user_cols:
            batch_op.add_column(sa.Column('animated_border_color', sa.String(length=7), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('animated_border_color')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('animated_border_color')

    # ### end Alembic commands ###
