"""add animated_border_color

Revision ID: c1b4990c90c4
Revises: 15a65ee2d30b
Create Date: 2026-08-02 23:50:09.814128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b4990c90c4'
down_revision = '15a65ee2d30b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('animated_border_color', sa.String(length=7), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('animated_border_color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('animated_border_color')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('animated_border_color')

    # ### end Alembic commands ###
