"""Auto migration

Revision ID: c3fd0b9cee83
Revises: b19ff7cb2c6f
Create Date: 2026-08-22 11:42:55.254757

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c3fd0b9cee83'
down_revision = 'b19ff7cb2c6f'
branch_labels = None
depends_on = None


def upgrade():
    # drop ghost tables if they exist
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_users")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('can_chat',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('can_chat',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###
