"""add_packets_awarded

Revision ID: dfb63a8729a5
Revises: d4c5e6f7a8b9
Create Date: 2026-07-05 22:43:36.588510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb63a8729a5'
down_revision = 'd4c5e6f7a8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_cols = [c['name'] for c in inspector.get_columns('projects')]
    if 'packets_awarded' not in existing_cols:
        with op.batch_alter_table('projects', schema=None) as batch_op:
            batch_op.add_column(sa.Column('packets_awarded', sa.Double(), nullable=False, server_default='0.0')) # noqa: lint-migrations
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('packets_awarded')
    # ### end Alembic commands ###
