"""Normalize models to use user_id instead of username

Revision ID: ea3252195b40
Revises: a1b2c3d4e5f6
Create Date: 2026-06-10 12:54:08.498310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ea3252195b40'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    if 'trade' in existing_tables:
        op.drop_table('trade')
    if 'bounties' in existing_tables:
        op.drop_table('bounties')
    with op.batch_alter_table('challenge_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('duck_trade_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    op.execute("UPDATE challenge_logs SET user_id = (SELECT id FROM users WHERE LOWER(users.username) = LOWER(challenge_logs.username))")
    op.execute("UPDATE duck_trade_log SET user_id = (SELECT id FROM users WHERE LOWER(users.username) = LOWER(duck_trade_log.username))")
    # Delete orphan logs if user_id is still NULL
    op.execute("DELETE FROM challenge_logs WHERE user_id IS NULL")
    op.execute("DELETE FROM duck_trade_log WHERE user_id IS NULL")

    with op.batch_alter_table('challenge_logs', schema=None) as batch_op:
        batch_op.alter_column('user_id', existing_type=sa.Integer(), nullable=False)
        try:
            batch_op.drop_index(batch_op.f('ix_challenge_logs_username'))
        except ValueError:
            pass  # Index may not exist in all environments
        batch_op.create_index(batch_op.f('ix_challenge_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_challenge_logs_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('username')

    with op.batch_alter_table('duck_trade_log', schema=None) as batch_op:
        batch_op.alter_column('user_id', existing_type=sa.Integer(), nullable=False)
        try:
            batch_op.drop_index(batch_op.f('ix_duck_trade_log_username'))
        except ValueError:
            pass  # Index may not exist in all environments
        batch_op.create_index(batch_op.f('ix_duck_trade_log_user_id'), ['user_id'], unique=False)
        try:
            batch_op.drop_constraint('fk_duck_trade_log_username_users', type_='foreignkey')
        except (ValueError, KeyError):
            pass  # Constraint may not exist in all environments
        batch_op.create_foreign_key(batch_op.f('fk_duck_trade_log_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duck_trade_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_duck_trade_log_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_duck_trade_log_username_users'), 'users', ['username'], ['username'])
        batch_op.drop_index(batch_op.f('ix_duck_trade_log_user_id'))
        batch_op.create_index(batch_op.f('ix_duck_trade_log_username'), ['username'], unique=False)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('challenge_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_challenge_logs_user_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_challenge_logs_user_id'))
        batch_op.create_index(batch_op.f('ix_challenge_logs_username'), ['username'], unique=False)
        batch_op.drop_column('user_id')

    op.create_table('bounties',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('bounty', sa.VARCHAR(), nullable=False),
    sa.Column('expected_behavior', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('digital_ducks_traded', sa.INTEGER(), nullable=False),
    sa.Column('duck_breakdown', sqlite.JSON(), nullable=False),
    sa.Column('duck_type', sa.VARCHAR(length=4), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
