"""Auto migration

Revision ID: f443a8f8f605
Revises: c3fd0b9cee83
Create Date: 2026-09-02 18:41:42.699781

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f443a8f8f605'
down_revision = 'c3fd0b9cee83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'track_change_requests' in inspector.get_table_names():
        with op.batch_alter_table('track_change_requests', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_track_change_requests_student_id_status'))
        op.drop_table('track_change_requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_change_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('requester_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('requested_track', sa.VARCHAR(length=50), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_track_change_requests_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_track_change_requests'))
    )
    with op.batch_alter_table('track_change_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_change_requests_student_id_status'), ['student_id', 'status'], unique=False)

    # ### end Alembic commands ###
